### ISSUE TITLE
Historias de Usuario Definición

### ISSUE THREAD

**Issue by tianitol** [tianitol/DEV002-social-network#3]
**Consideraciones, README**

    Debe ser una SPA.
    Debe ser responsive.
    Deben haber recibido code review de al menos una compañera de otro equipo.
    Hicieron los test unitarios
    Testearon manualmente buscando errores e imperfecciones simples.
    Hicieron pruebas de usabilidad e incorporaron el feedback de los usuarios como mejoras.
    Desplegaron su aplicación y etiquetaron la versión (git tag).

5.3 Historias de usuario

Una vez que entiendas las necesidades de tus usuarixs, escribe las Historias de Usuario que representen todo lo que necesitan hacer/ver en la Red Social. Cada una de tus Historias de Usuario debe tener:

    Criterios de Aceptación: todo lo que debe ocurrir para satisfacer las necesidades del usuario.

    Definición de terminado: todos los aspectos técnicos que deben cumplirse para que, como equipo, sepan que esa historia está terminada y lista para publicarse. Todas tus Historias de Usuario (salvo excepciones), deben incluir estos aspectos en su Definición de Terminado (más todo lo que necesiten agregar):
        Debe ser una SPA.
        Debe ser responsive.
        Deben haber recibido code review de al menos una compañera de otro equipo.
        Hicieron los test unitarios
        Testearon manualmente buscando errores e imperfecciones simples.
        Hicieron pruebas de usabilidad e incorporaron el feedback de los usuarios como mejoras.
        Desplegaron su aplicación y etiquetaron la versión (git tag).

5.4 Diseño de la Interfaz de Usuario (prototipo de baja fidelidad)

Debes definir cuál será el flujo que seguirá el usuario dentro de tu aplicación y, con eso, diseña la Interfaz de Usuario (UI por sus siglas en inglés) que siga este flujo.
5.5 Responsive

Debe verse bien en dispositivos de pantallas grandes (computadoras/es, laptops, etc.) y pequeñas (tablets, celulares, etc.). Te sugerimos seguir la técnica de mobile first (más detalles sobre esta técnica al final).
5.6 Consideraciones del comportamiento de la interfaz de usuario (UI)

Estas consideraciones te ayudarán a escribir las Definiciones de Terminado de tus H.U.:
Creación de cuenta de usuario e inicio de sesión

    Login con Firebase:
        Para el login y las publicaciones en el muro puedes utilizar [Firebase](https://firebase.google.com/products/database/)
        Creación de cuenta de acceso y autenticación con cuenta de correo y contraseña, y también con una cuenta de Google.
    Validaciones:
        Solamente se permite el acceso a usuarios con cuentas válidas.
        No pueden haber usuarios repetidos.
        La cuenta de usuario debe ser un correo electrónico válido.
        Lo que se escriba en el campo (input) de contraseña debe ser secreto.
    Comportamiento:
        Al enviarse el formulario de registro o inicio de sesión, debe validarse.
        Si hay errores, se deben mostrar mensajes descriptivos para ayudar al usuario a corregirlos.

Muro/timeline

    Validaciones:
        Al publicar, se debe validar que exista contenido en el input.
    Comportamiento:
        Al recargar la aplicación, se debe verificar si el usuario está logueado antes de mostrar contenido.
        Poder publicar un post.
        Poder dar y quitar like a una publicación. Máximo uno por usuario.
        Llevar un conteo de los likes.
        Poder eliminar un post específico.
        Pedir confirmación antes de eliminar un post.
        Al dar click para editar un post, debe cambiar el texto por un input que permita editar el texto y luego guardar los cambios.
        Al guardar los cambios debe cambiar de vuelta a un texto normal pero con la información editada.
        Al recargar la página debo de poder ver los textos editados.

5.7 Consideraciones técnicas Front-end

    Separar la manipulación del DOM de la lógica (Separación de responsabilidades).
    Contar con múltiples vistas. Para esto, tu aplicación debe ser una [Single Page Application (SPA)](https://es.wikipedia.org/wiki/Single-page_application)
    Alterar y persistir datos. Los datos que agregues o modifiques deberán persistir a lo largo de la aplicación. Te recomendamos que uses [Firebase](https://firebase.google.com/) para eso también.

Pruebas unitarias (unit tests)

    Recuerda que no hay un setup de tests definido, dependerá de la estructura de tu proyecto. Algo que no debes de olvidar es pensar en éstas pruebas, te pueden ayudar a definir la estructura y nomenclatura de tu lógica.

    Los tests unitarios deben cubrir un mínimo del 70% de statements, functions, lines, y branches.

5.8 Consideraciones técnicas UX

    Hacer al menos 2 entrevistas con usuarios.
    Hacer un prototipo de baja fidelidad.
    Asegurarte de que la implementación en código siga los lineamientos del diseño.
    Hacer sesiones de testing de usabilidad con el producto en HTML.

**Comment by tianitol** [comment]
**HU1**

Cómo: Nuevo usuario
Quiero: poder registrarme 
Para: acceder al sitio web por primera vez

Criterios de aceptación:
- Que aparezca un formulario para ingresar los datos de creación de cuenta (Correo electrónico(google), Contraseña)
-  Lo que se escriba en el campo (input) de contraseña debe ser secreto.
- Que haya un botón de envío del formulario
- Validación: Que no se permita enviar el formulario en los siguientes casos (vacío o con alguno de los campos faltantes, correo invalido, contraseña que no cumpla lo requerido,  no pueden haber usuarios repetidos).
- Si hay errores, se deben mostrar mensajes descriptivos para ayudar al usuario a corregirlos.
- Es fiel a los estilos definidos según prototipo de alta fidelidad



Definición de terminado:

- Debe ser una SPA.
-     Debe ser responsive.
-     Deben haber recibido code review de al menos una compañera de otro equipo.
-     Hicieron los test unitarios
-     Testearon manualmente buscando errores e imperfecciones simples.
-     Hicieron pruebas de usabilidad e incorporaron el feedback de los usuarios como mejoras.
-     Desplegaron su aplicación y etiquetaron la versión (git tag).



**HU2**

Cómo: Usuario registrado
Quiero: loguearme 
Para: ingresar a la app 

Criterios de aceptación:
- Se presenta un botón (login) que al hacer click aparezca el formulario de ingreso
- Se presente un formulario con dos campos (correo(google) y contraseña)
- Se presente botón para envío de formulario ("login" o "acceder") 
_**Para otra HU agregar botón (formulario) para recordar contraseña_
- Validaciones (correo válido, contraseña registrada, sin campos vacíos)
- Si hay errores, se deben mostrar mensajes descriptivos para ayudar al usuario a corregirlos.
- Es fiel a los estilos definidos según prototipo de alta fidelidad



Definición de terminado:
- Debe ser una SPA.
-     Debe ser responsive.
-     Deben haber recibido code review de al menos una compañera de otro equipo.
-     Hicieron los test unitarios
-     Testearon manualmente buscando errores e imperfecciones simples.
-     Hicieron pruebas de usabilidad e incorporaron el feedback de los usuarios como mejoras.
-     Desplegaron su aplicación y etiquetaron la versión (git tag).

**Comment by JhoannaR** [comment]
![Image](https://user-images.githubusercontent.com/113317909/209192327-69a36468-b8da-41e7-803b-abf4d27e953f.PNG)

**Comment by Valmontx** [comment]
HU 3 

Cómo: Usuario logueado
Quiero: poder visualizar los post existentes
Para: poder interactuar (like , *comentar , *compartir )

Criterios de aceptación 

Validaciones:

- [ ] Al recargar la aplicación, se debe verificar si el usuario está logueado antes de mostrar contenido.
- [ ] Poder dar y quitar like a una publicación. Máximo uno por usuario.
- [ ] Llevar un conteo de los likes.

Definición de terminado:




HU 4 
Cómo: Usuario logueado
Quiero: poder postear  (*privacidad del muro *imágenes )
Para: poder interactuar con los otros usuarios

Criterios de aceptación 

 Validaciones:

- [ ] Poder publicar un post solo si se encuentra logueado.
- [ ] Al publicar, se debe validar que exista contenido en el input.
- [ ] Llevar un conteo de los likes.
- [ ] Poder eliminar un post específico.
- [ ] Pedir confirmación antes de eliminar un post.
- [ ] Al dar click para editar un post, debe cambiar el texto por un input que permita editar el texto y luego guardar los cambios.
- [ ] Al guardar los cambios debe cambiar de vuelta a un texto normal pero con la información editada.
- [ ] Al recargar la página debo de poder ver los textos editados.

Definición de terminado

**Comment by Valmontx** [comment]
HU 4 
Cómo: Usuario logueado
Quiero: poder postear  (*privacidad del muro)
Para: poder interactuar con los otros usuarios

Criterios de aceptación 
  Se ve los post existentes en tiempo real.
 


 Validaciones:

- [ ] Poder publicar un post solo si se encuentra logueado.
- [ ] Al publicar, se debe validar que exista contenido en el input.
- [ ] Capturar el id del usuario - descripción - fecha.
- [ ] Utilizar el onSnapshot para poder actualizar en tiempo real.
- [ ] Implementación del logout

**Comment by Valmontx** [comment]
HU 5 
 Como : Usuario logueado 
 Quiero : poder editar mi propio post.
 Para: Poder corregir y complementar lo escrito.

Validaciones : 

- [ ]  Solo mostrar la opción editar si es el mismo usuario que la creo.

Criterios de aceptación:
 

- [ ] Se muestra el post editado en tiempo real 
- [ ] Mantener el texarea fijado para poder editar o postear mientras se hace scroll en feed
- [ ]

**Comment by Valmontx** [comment]
HU 6 
Como:  Usuario logueado
Quiero : poder eliminar mi propio post.
Para : que no se muestre 

Validaciones : 
 

- [ ] Solo mostrar la opcion eliminar al usuario que posteo ese post 

Criterios de aceptación : 

- [ ]  Mostrar un modal al eliminar un post dando opción de aceptar o cancelar. 
- [ ] Eliminar un post y actualizar en tiempo real

**Comment by Valmontx** [comment]
HU 7 
Como: Usuario logueado
Quiero: poder dar like a un post y visualizar los likes que tiene un post.
Para: demostrar que me agrado el post publicado y saber cuales son los post con mas interacción .

Validaciones : 

- [ ] Solo poder dar like una vez por usuario.
- [ ] Poder quitar el like con el mismo botón al presionar por segunda vez.

Criterios de aceptación:

- [ ] Poder visualizar el botón del like.
- [ ] Poder ver el cambio del color del botón al momento de dar like.
- [ ] Visualizar el conteo de likes 
- [ ] Se muestre el cambio en tiempo real
