### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by Valmontx** [tianitol/DEV002-social-network#5]
https://www.youtube.com/watch?v=1rLBjRF0ep0
Firebase Auth | Authentication de Gmail

**Comment by tianitol** [comment]
[Primeros pasos con Firebase Authentication en sitios web.pdf](https://github.com/tianitol/DEV002-social-network/files/10296514/Primeros.pasos.con.Firebase.Authentication.en.sitios.web.pdf)

[Paso a paso de la autenticación con correo y contraseña (documentación de Firebase) .pdf](https://github.com/tianitol/DEV002-social-network/files/10296515/Paso.a.paso.de.la.autenticacion.con.correo.y.contrasena.documentacion.de.Firebase.pdf)

[Autentica mediante el Acceso con Google y JavaScript.pdf](https://github.com/tianitol/DEV002-social-network/files/10296523/Autentica.mediante.el.Acceso.con.Google.y.JavaScript.pdf)




- Autenticación rapida con firebase https://platzi.com/blog/autenticacion-con-firebase-en-5-minutos/

**Comment by JhoannaR** [comment]
![Image](https://user-images.githubusercontent.com/113317909/209677929-142a3231-aa08-4c7a-845b-92dcb99365b2.png)

**Comment by Valmontx** [comment]
https://www.youtube.com/watch?v=D8bBmnDQ7ZA 
firebase - catching error
